### ISSUE TITLE
网卡如何安装？

### ISSUE THREAD

**Issue by Onicc** [FTWH/asrock-h470m-itx-opencore-i5-10500-RX5700-EFI#1]
您好，我看到您装了两个固态和一个显卡，请问网卡怎么安装的，我现在找不到安装的地方，期待您的回复，谢谢！

**Comment by Onicc** [comment]
不好意思 我知道如何安装了

**Comment by FTWH** [comment]
无线网卡需要替换主板上的网卡


在 2021年5月28日 ***@***.***> 写道：


您好，我看到您装了两个固态和一个显卡，请问网卡怎么安装的，我现在找不到安装的地方，期待您的回复，谢谢！
